version: '3.4'

services:
  confluence:
    image: cptactionhank/atlassian-confluence:7.9.3
    container_name: confluence
    ports:
    - "8090:8090"
    - "8091:8091"
    restart: always
    links:
        - postgres
    volumes:
        - ./logs:/opt/atlassian/confluence/logs
        - ./confluence-data:/var/atlassian/confluence

  postgres:
    image: postgres
    container_name: postgresql
    tty: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confluence
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    hostname: postgres
    restart: always
    user: postgres
    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin:/root/.pgadmin
    hostname: pgadmin4
    restart: always